version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: biblioteka-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: abcd1234
      MYSQL_DATABASE: biblioteka
    ports:
      - "3306:3306"
    volumes:
      - ./biblioteka.sql:/docker-entrypoint-initdb.d/biblioteka.sql
